### ISSUE TITLE
Accessing Events and Venues content pages from plugin settings page gives 404

### ISSUE THREAD

**Issue by victorkane** [pencilblue/calendar-pencilblue#10]
According to [the instructions](https://pencilblue.org/plugins/view/54cc2a5ac03ea90074829437):

> 4. ...Click on the Venue button on the calender-pencilblue settings screen and add a venue object.
> 5. Go back to the calendar-pencilblue plugins settings screen and click on the Events button (both venues and events are custom objects, so you can also reach them from the standard manage custom objects screen). Create an event and save.

However clicking on either Events or Venues button from the plugin settings page redirects to 404 

I got `http://example.com:8040/admin/content/custom_objects/manage_objects/552f9be490afd3a12d3373f5`

However, events and venues CRUD objects work perfectly well at Content > Custom objects

**Comment by brianhyder** [comment]
@victorkane Thank you for reporting!
