### ISSUE TITLE
Error on display calendar

### ISSUE THREAD

**Issue by colomboipl** [pencilblue/calendar-pencilblue#12]
After install this puglin and create a venue and event on the custom objects on admin page. When I open a page with the calendar object it appears this error :+1: 
"TypeError: Cannot read property 'length' of undefined
    at formatEvent (/home/arnaldo/Desktop/pencilblue/pencilblue/plugins/calendar-pencilblue/calendar.js:231:38)"

**Comment by maxmedresearch** [comment]
Same error after install:  "TypeError: Cannot read property 'length' of undefined
at formatEvent (/calendar-pencilblue/calendar.js:231:38)"

**Comment by brianhyder** [comment]
Thank you for the heads up guys.  We'll dive into it and see what the issue
is.  If you create an event does the error go away?

On Wed, May 20, 2015 at 5:42 AM, maxmedresearch <notifications@github.com>
wrote:

> Same error after install: "TypeError: Cannot read property 'length' of
> undefined
> at formatEvent (/calendar-pencilblue/calendar.js:231:38)"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/calendar-pencilblue/issues/12#issuecomment-103826111>
> .
>



-- 
Brian P. Hyder

**Comment by colomboipl** [comment]
No, the error persists with events added.

**Comment by colomboipl** [comment]
No, the error persists with events added.

**Comment by colomboipl** [comment]
Sorry I just closed this issue without knowing. Sorry, this Issue is still OPEN

**Comment by brianhyder** [comment]
I wanted to say thank you for reporting the bug.  I merged the fix moments ago.  Please let me know if you find any other issues.

The underlying cause was that in the recent months we update the mongo driver.  In MongoDB v2.6 they became more strict about how the "order" syntax was structured.  I modified the syntax and made a few other improvements while I was in there.
